/// Flutter icons WuoofAppIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WuoofAppIcons
///      fonts:
///       - asset: fonts/WuoofAppIcons.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class WuoofAppIcons {
  WuoofAppIcons._();

  static const _kFontFam = 'WuoofAppIcons';
  static const _kFontPkg = null;

  static const IconData iconos_wuoof_tarjetas = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guidedog = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconos_wuoof_actividad = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconos_wuoof_an_adirmascota = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconos_wuoof_cerrarsesio_n = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconos_wuoof_inbox_03__1_ = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconos_wuoof_an_adirmascota_05 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
